{{- if and .Values.openshift.enabled .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "openfilz-web.fullname" . }}
  labels: {{- include "openfilz-web.labels" . | nindent 4 }}
spec:
  {{- with (.Values.openshift.route.hostname | default (include "openfilz-web.hostWeb" .)) }}
  host: {{ . }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "openfilz-web.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
    {{- with .Values.openshift.route.tls.key }}
    key: |-
      {{- . | nindent 6 }}
    {{- end }}
    {{- with .Values.openshift.route.tls.certificate }}
    certificate: |-
      {{- . | nindent 6 }}
    {{- end }}
    {{- with .Values.openshift.route.tls.caCertificate }}
    caCertificate: |-
      {{- . | nindent 6 }}
    {{- end }}
    {{- with .Values.openshift.route.tls.destinationCACertificate }}
    destinationCACertificate: |-
      {{- . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
